### ISSUE TITLE
Could not create widget

### ISSUE THREAD

**Issue by MrJer** [tieniber/DataGridColumnSearch#14]
Mendix runtime showed "Could not create widget DataGridColumnSearch.widget.DataGridColumnSearch" on page.

No error message shown in console. Modeler version 7.23.3.

**Comment by MrJer** [comment]
Verbose message in console showed the process failed at postCreate function

**Comment by tieniber** [comment]
This widget must be placed under the data grid on the page. This is
counter-intuitive. Any chance that’s your problem?

**Comment by MrJer** [comment]
Thank you for suggesting that. I gave it a try and, although it was able to generate search fields on the column, the bottom of the page still showed "Could not create widget DataGridColumnSearch.widget.DataGridColumnSearch". Also, the content in the grid was not responding to value change in search field.

**Comment by MaikCape** [comment]
I have the same problem in Mendix 7.23.3. The widget doesn't have problems in earlier versions (in this project we use this widget since Mendix 7.16.0 and we migrated from 7.22.2 to 7.23.3). Also in another project which we want to migrate from Mendix 7.16.0 to 7.23.3 we have the same problem.

I see the following error in the browserconsole. 

mxui.js?636917201332645837:79 Error: Shipment.FlakeTransport_Overview_Kien.tabContainer1: Error while applying context Error: : Error while applying context Error: Shipment.FlakeTransport_Overview_Kien.dataGridColumnSearch1: Error while applying context Error: Shipment.FlakeTransport_Overview_Kien.dataGridColumnSearch1: Error while applying context TypeError: Cannot read property 'children' of undefined
    at mxui.js?636917201332645837:46
    at Object.e.exports.collect (mxui.js?636917201332645837:20)
    at Object.e.exports.applyContext (mxui.js?636917201332645837:46)
    at mxui.js?636917201332645837:46
    at o (mxui.js?636917201332645837:20)
    at Object.e.exports.sequence (mxui.js?636917201332645837:20)
    at Object.e.exports.fireOnReady (mxui.js?636917201332645837:46)
    at mxui.js?636917201332645837:46
    at Object.e.exports.collect (mxui.js?636917201332645837:20)
    at e.exports.loadWidgetsIn (mxui.js?636917201332645837:46)

**Comment by tieniber** [comment]
Thanks. @MaikCape, are one or more of your columns dates? I think that perhaps the date picker widget changed in 7.23.3. I'll dig into this soon, but I am curious what happens if you remove the date field(s).

**Comment by MaikCape** [comment]
@tieniber Yes one or more of the columns are dates. When I remove the date fields the widget is loaded correctly. 

So indeed it looks like something is changed in the date picker widget. 

Thanks for your fast reply, I hope you can solve it so we can keep using this widget.

**Comment by tieniber** [comment]
fixed in 1.5.2

**Comment by rajnish87k** [comment]
I am getting the same error:  Could not create widget DataGridColumnSearch.widget.DataGridColumnSearc,
While using the date as column in Datagrid for the 8.4.2 version
